[build]
  publish = "frontend"

[[redirects]]
  from = "/api/*"
  to = "https://backend-git-main-shreya-sahus-projects-6949e5da.vercel.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200